### ISSUE TITLE
bash: grunt: command not found

### ISSUE THREAD

**Issue by puyanbiao** [jaywcjlove/websocket#2]
为什么在命令行输入 grunt后，提示bash: grunt: command not found，我漏了哪一步呢？已经根目录下了的

**Comment by jaywcjlove** [comment]
@puyanbiao 这都好久的玩意儿，太老了，运行都报错，Node.js API都变了，修复了一下

`Gruntfile.coffee` 文件没有用了，要装 coffeescript， 整了个 `Gruntfile.js`，现在能跑起来了

```bash
npm install #安装依赖
npm start
```

**Comment by puyanbiao** [comment]
可以跑起来的，谢谢！

在 2018-10-22 22:19:41，"小弟调调™" <notifications@github.com> 写道：


@puyanbiao 这都好久的玩意儿，太老了，运行都报错，Node.js API都变了，修复了一下

Gruntfile.coffee 文件没有用了，要装 coffeescript， 整了个 Gruntfile.js，现在能跑起来了

先起后台

npm install #安装依赖
node server.js

运行

npm run start
